#!/bin/bash

umask 0022
export RAILS_ENV=production

cmds=(
  'bundle install'
  'bundle exec rake db:migrate'
  'bundle exec rake assets:precompile'
  'echo "BlogTest::Application.config.secret_token = "'$(bundle exec rake secret)'"" > config/initializers/secret_token.rb'
)

# --

for cmd in "${cmds[@]}"; do
  echo "==> $cmd"
  time $cmd
done

# --
