#!/bin/bash

umask 0022
export RAILS_ENV=production

cmds=(
  'bundle install'
  'bundle exec rake db:migrate'
  'bundle exec rake assets:precompile'
  'bundle exec rake generate_secret_token'
)

# --

for cmd in "${cmds[@]}"; do
  echo "==> $cmd"
  time $cmd
done

# --
